[package]
name = "embassy-rp-pio-usb-host"
version = "0.3.0"
edition = "2024"
rust-version = "1.93"
license = "MIT OR Apache-2.0"
description = "Experimental full- and low-speed PIO USB host for RP2040 and RP2350 using Embassy"
homepage = "https://github.com/ulso/embassy-rp-pio-usb-host"
repository = "https://github.com/ulso/embassy-rp-pio-usb-host"
documentation = "https://github.com/ulso/embassy-rp-pio-usb-host#readme"
readme = "README.md"
keywords = ["embassy", "embedded", "pio", "rp2040", "usb-host"]
categories = ["embedded", "hardware-support", "no-std"]
publish = false
autoexamples = false

[features]
default = ["embassy-usb-host", "rp2040"]
analyzer-capture = []
embassy-usb-host = ["dep:embassy-usb-host"]
rp2040 = ["embassy-rp/rp2040"]
rp235xa = ["embassy-rp/rp235xa"]

[dependencies]
embassy-sync = "=0.8.0"
embassy-usb-driver = "=0.2.2"
embedded-io-async = "=0.7.0"
embassy-usb-host = { version = "=0.1.0", optional = true }

[lib]
test = true

[[bin]]
name = "pio-usb-host"
path = "src/main.rs"
test = false
bench = false
required-features = ["embassy-usb-host"]

[[example]]
name = "bleuio"
path = "examples/bleuio.rs"
test = false
bench = false
required-features = ["embassy-usb-host"]

[[example]]
name = "p8055"
path = "examples/p8055.rs"
test = false
bench = false
required-features = ["embassy-usb-host"]

[target.'cfg(target_os = "none")'.dependencies]
cortex-m = "0.7.7"
cortex-m-rt = "0.7.5"
defmt = "1.0.1"
defmt-rtt = "1.0.0"
embassy-executor = { version = "0.10.0", features = ["defmt", "executor-thread", "platform-cortex-m"] }
embassy-futures = "=0.1.2"
embassy-rp = { version = "=0.10.0", features = ["critical-section-impl", "defmt", "time-driver", "unstable-pac"] }
embassy-time = { version = "0.5.1", features = ["defmt", "defmt-timestamp-uptime"] }
fixed = "=1.31.0"
panic-probe = { version = "1.0.0", features = ["print-defmt"] }
pio = "0.3.0"

[profile.release]
debug = 2
lto = "fat"
opt-level = "s"
codegen-units = 1

[profile.dev]
debug = 2
opt-level = 1
